platform :ios, '9.0'
use_frameworks!
inhibit_all_warnings!

install! 'cocoapods', :deterministic_uuids => false

abstract_target '17k' do
  
  target 'TestOC' do
    
    #阅读 SDK 注意路径
    pod 'Reader17kSDK',    :path => './..'
    
    # === 以下非必需，demo 测试所用 === #
    # 穿山甲广告
    pod 'Ads-CN'
    # 自动布局
    pod 'Masonry'
    
  end


end

# 兼容调整
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # deployment target
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      # pie warning
      config.build_settings['LD_NO_PIE'] = 'NO'
    end
  end
end
